services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scit-nextjs
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production

    networks:
      - scit-net

networks:
  scit-net:
    external: true
